bible_verses = [
    "John 3:16 - For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    "Philippians 4:13 - I can do all things through Christ who strengthens me.",
    "Jeremiah 29:11 - For I know the plans I have for you, declares the LORD, plans for welfare and not for evil, to give you a future and a hope.",
    "Romans 8:28 - And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    "Proverbs 3:5 - Trust in the LORD with all your heart and lean not on your own understanding.",
    "Psalm 23:1 - The LORD is my shepherd; I shall not want.",
    "Isaiah 41:10 - So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.",
    "Matthew 11:28 - Come to me, all you who are weary and burdened, and I will give you rest.",
    "Joshua 1:9 - Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.",
    "1 Peter 5:7 - Cast all your anxiety on him because he cares for you.",
    "John 14:27 - Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.",
    "Psalm 46:1 - God is our refuge and strength, an ever-present help in trouble.",
    "2 Timothy 1:7 - For God has not given us a spirit of fear, but of power and of love and of a sound mind.",
    "Isaiah 40:31 - But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.",
    "Matthew 6:34 - Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.",
    "Proverbs 18:10 - The name of the LORD is a strong tower; the righteous run to it and are safe.",
    "Romans 15:13 - May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.",
    "1 Corinthians 13:4-7 - Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.",
    "Psalm 121:1-2 - I lift up my eyes to the mountains— where does my help come from? My help comes from the LORD, the Maker of heaven and earth.",
    "Romans 12:2 - Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is—his good, pleasing and perfect will.",
    "Psalm 19:14 - May these words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer.",
    "Colossians 3:23 - Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.",
    "James 1:5 - If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.",
    "Ephesians 2:8 - For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.",
    "Hebrews 11:1 - Now faith is confidence in what we hope for and assurance about what we do not see.",
    "1 John 4:7 - Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God.",
    "1 Corinthians 10:13 - No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.",
    "Psalm 34:8 - Taste and see that the LORD is good; blessed is the one who takes refuge in him.",
    "Psalm 139:14 - I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.",
    "Romans 5:8 - But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
    "Isaiah 43:2 - When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.",
    "Micah 6:8 - He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.",
    "Hebrews 4:12 - For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.",
    "Psalm 30:5 - For his anger lasts only a moment, but his favor lasts a lifetime; weeping may stay for the night, but rejoicing comes in the morning.",
    "2 Chronicles 7:14 - If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land.",
    "John 16:33 - I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.",
    "Galatians 5:22-23 - But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.",
    "1 Thessalonians 5:11 - Therefore encourage one another and build each other up, just as in fact you are doing.",
    "Exodus 14:14 - The LORD will fight for you; you need only to be still.",
    "Lamentations 3:22-23 - Because of the LORD’s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
    "Proverbs 31:25 - She is clothed with strength and dignity; she can laugh at the days to come.",
    "Psalm 91:1-2 - Whoever dwells in the secret place of the Most High will rest in the shadow of the Almighty. I will say of the LORD, “He is my refuge and my fortress, my God, in whom I trust.”",
    "Zephaniah 3:17 - The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.",
    "Psalm 73:26 - My flesh and my heart may fail, but God is the strength of my heart and my portion forever."
]
